apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: $KAFKACLUSTER
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}	  
      external:
        type: ingress
        configuration:
          bootstrap:
            host: $KAFKACLUSTER-bootstrap-$PROJECT.$KAFKADNS
          brokers:
          - broker: 0
            host: $KAFKACLUSTER-broker-0-$PROJECT.$KAFKADNS
          - broker: 1
            host: $KAFKACLUSTER-broker-1-$PROJECT.$KAFKADNS
          - broker: 2
            host: $KAFKACLUSTER-broker-2-$PROJECT.$KAFKADNS			
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: $STORAGECLASS
        size: $KAFKAPVC
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: $STORAGECLASS	  
      size: $KAFKAPVC
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
